# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: demo

# The type of the application to build.
type: php:7.0

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "dbserver:mysql"
    solr: "searchserver:solr"

dependencies:
  ruby:
    sass: "3.4.7"


# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: "/"
    # The front-controller script to send non-static requests to.
    passthru: "/index.php"

# The size of the persistent disk of the application (in MB).
disk: 256

# The mounts that will be performed when the package is deployed.
#mounts:
#    "/storage": "shared:files/storage"
# The hooks that will be performed when the package is deployed.
#hooks:
#    deploy: |
#        php artisan migrate --force
#    build: |
#        cd webapp
#        npm install
#        bower install
#        gulp
# The configuration of scheduled execution.
# see http://symfony.com/doc/current/components/console/introduction.html
#crons:
#    symfony:
#        spec: "*/20 * * * *"
#        cmd: "php cron.php example:test"
